### ISSUE TITLE
avro_encode_error when encoding CE with Avro

### ISSUE THREAD

**Issue by KaWigg** [kevinbader/cloudevents-ex#2]
I have a simple Avro schema for testing

`{
  "type": "record",
  "name": "Exampleschema",
  "fields": [
    {"name": "example", "type": "string"}
  ]
}`

and starting Cloudevents with

`Cloudevents.start_link([{:confluent_schema_registry_url, "http://schema-registry:8081"},
      {:avro_schemas_path, "./priv/schemas"},
      {:avro_event_schema_name, "Exampleschema"}])`

The schema-registry is reachable through docker, and my schema lives in `./priv/schemas/Exampleschema.avsc`

I copied over the event from one of your examples to make sure I'm not missing anything

```
event = Cloudevents.from_map!(%{specversion: "1.0",type: "some-type",source: "some-source",id: "1",data: %{"example" => "bar"}})                            
%Cloudevents.Format.V_1_0.Event{ 
  data: %{"example" => "bar"},
  datacontenttype: "application/json",
  dataschema: nil,
  extensions: %{},
  id: "1",
  source: "some-source",
  specversion: "1.0",
  subject: nil,
  time: nil,
  type: "some-type"
}
```

when i try to encode it with avro, I get the following

```
event |> Cloudevents.to_avro                                                                                                                                    
[debug] reading schema `Exampleschema` from the file ./priv/schemas/Exampleschema.avsc
[debug] new schema `Exampleschema` stored with global id `121`
{:error,
 %ErlangError{
   original: {:"$avro_encode_error", :required_field_missed,
    [record: "Exampleschema", field: "example"]}
 }}
```

but the field is there in the data map.

**Comment by kevinbader** [comment]
Hi @KaWigg - the schema refers to the whole thing, not just to `data`. There is currently no way to produce a JSON encoded CloudEvent that carries an Avro-encoded `data` payload, if that's what you're trying to do here.

**Comment by KaWigg** [comment]
Hi @kevinbader 
Thats not what I wanted to do but I got now, what I was doing wrong. Thanks for the clarification! I expanded the schema to match the whole event, not only the data field and it works as intended.

Thanks again!
