### ISSUE TITLE
erlavro is a dependency of this project and it uses Rebar 2

### ISSUE THREAD

**Issue by brooksmtownsend** [kevinbader/cloudevents-ex#5]
```
dependency :erlavro is using Rebar 2, which is no longer maintained and no longer works in recent Erlang/OTP versions. Remove the :manager option or set it to :rebar3 instead
```

I get this warning when using this package

**Comment by brooksmtownsend** [comment]
I can fix it with an override, but it could easily be upgraded here
```
      {:erlavro, "~> 2.9.7", override: true, manager: :rebar3}
```

**Comment by brooksmtownsend** [comment]
Alternatively, if `avrora` was an optional dependency then this would only be needed if you brought in the optional avro dependencies

**Comment by kevinbader** [comment]
Hi @brooksmtownsend, thanks for reporting. Happy to review a PR if you‘d like to contribute! Otherwise it’ll take some time for me to look into this, as I’m currently busy with other projects (which aren’t related to Elixir and Cloudevents)

**Comment by brooksmtownsend** [comment]
@kevinbader thanks for the quick response! I'd be happy to contribute, at the base level I can update the erlavro dependency and that should help everyone using this package.

I'm curious though, would you be fine with me making erlavro an optional dependency in addition to updating it? JSON is required, but we (and likely others) use this library without Avro and that would avoid bringing in extra dependencies (and for what it's worth I think we even got a build failure from one of them that we had to work around)

**Comment by kevinbader** [comment]
> I'm curious though, would you be fine with me making erlavro an optional dependency in addition to updating it? JSON is required, but we (and likely others) use this library without Avro and that would avoid bringing in extra dependencies (and for what it's worth I think we even got a build failure from one of them that we had to work around)

Sure, great idea!
