### ISSUE TITLE
Make Avro dependency optional

### ISSUE THREAD

**Issue by kevinbader** [kevinbader/cloudevents-ex#9]
I'm curious though, would you be fine with me making erlavro an optional dependency in addition to updating it? JSON is required, but we (and likely others) use this library without Avro and that would avoid bringing in extra dependencies (and for what it's worth I think we even got a build failure from one of them that we had to work around)

_Originally posted by @brooksmtownsend in https://github.com/kevinbader/cloudevents-ex/issues/5#issuecomment-1157841732_

**Comment by kevinbader** [comment]
oops, I was a bit too fast closing this - the code doesn't work, as Cloudevents fails to start in case Avrora is not there

**Comment by kevinbader** [comment]
haha my bad I forgot we only need the supervisor in case Avro is needed, so not an issue. I'll add a bit of code to improve the error message and that's it :)

**Comment by kevinbader** [comment]
done - fixed in 0.6.1.  (It was a long week ^^)

**Comment by brooksmtownsend** [comment]
Thank you @kevinbader, apologies for not catching this in my PR!
